# Ortam Bilgisi
environment=preprod
base.url=https://preprod.testfly.com

# preprod ortam? bazen yava?t?r, timeout art?r?ld?
timeout=20000

# Hata ay?klarken taray?c?y? g�rmek isteriz
headless=false

browser=chrome
record.video=false

# Log Seviyesi
log.level=INFO

# API Ayarlar?
api.timeout.connect=30000
api.timeout.read=30000
api.retry.max=3
api.retry.delay=1000